### ISSUE TITLE
Please could the provider support the User ID Authenticated checkbox within the Options selector for a Policy

### ISSUE THREAD

**Issue by darrensunley** [iwarapter/terraform-provider-pingfederate#248] opened 2022-12-19 11:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please can the provider support the setting of the User ID Authenticated checkbox within the Options selector for a Policy please. This was introduced in PF10 (and we've just upgraded from PF9 so found it!).

Normal authentication is fine without setting this value - however, when you have a PingID adapter then if you don't tick the checkbox (which relates to the incoming userID from an HTMLForm adapter, the previous step in our policy) then new users (or users pairing a new device) never get prompted for the enrollment process... so always fail authentication!

### New or Affected Resource(s)

/authenticationPolicies

### Potential Terraform Configuration

I suspect that the config should be something like the following...

```
              input_user_id_mapping {
                source {
                  type = "ADAPTER"
                  id   = pingfederate_idp_adapter.emp_all_attrs_form_adapt.id
                }
                value = "UserPrincipalName"
                useridauthenticated = true
              }
```

### References

https://docs.pingidentity.com/r/en-us/pingfederate-112/pf_specify_incoming_user_ids   (point 5)

**Comment by darrensunley** [comment] 2022-12-19 11:59
![pf10_user_ID_Authenticated_in_policy](https://user-images.githubusercontent.com/98756090/208421207-b5bfba3c-e555-42a7-872c-37fb62eb4f9d.jpg)

**Comment by iwarapter** [comment] 2022-12-21 17:31
duplicate of #215

**Closed by iwarapter** 2022-12-21 17:31 UTC
Labels: enhancement
