### ISSUE TITLE
Push configuration to clustered Engines

### ISSUE THREAD

**Issue by cprice-ping** [iwarapter/terraform-provider-pingfederate#219] opened 2022-09-07 15:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

HCL is applied to the Administrative node, but are not automatically pushed down to and Engine nodes in a cluster.

In order for the configuration to become "active", you need to connect to the Admin Console UI and manually replicate.

There is an API endpoint to perform this action -- POST `{{pfAdminURL}}/pf-admin-api/v1/cluster/replicate`

### New or Affected Resource(s)

* pingfederate_*

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here
```

### References

* #0000

**Comment by iwarapter** [comment] 2022-09-07 17:28
This is a duplicate of #98

**Closed by iwarapter** 2022-09-07 17:28 UTC
Labels: enhancement

**Comment by iwarapter** [comment] 2022-09-07 17:31
The common workaround for this at the moment is to just add a `curl` command after the apply has run (sucessfully)
